<?xml version="1.0" encoding="utf-8"?><Database Name="MyGraduationProjectDatabase" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-WebApplication1-20160819032236.mdf;Initial Catalog=MyGraduationProjectDatabase;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="DatabaseAccess.Properties.Settings" SettingsPropertyName="MyGraduationProjectDatabaseConnectionString" Provider="System.Data.SqlClient" />
</Database>