<?xml version="1.0" encoding="utf-8"?><Database Name="MyGraduationProjectDatabase" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=C:\Users\Misiek\Desktop\MyGraduationProject\MyGraduationProject\App_Data\aspnet-WebApplication1-20160819032236.mdf;Initial Catalog=MyGraduationProjectDatabase;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="DatabaseAccess.Properties.Settings" SettingsPropertyName="MyGraduationProjectDatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Connectors" Member="Connectors">
    <Type Name="Connector">
      <Column Name="CONNECTION_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ITEM_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VALUE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Connector" Member="Item" ThisKey="ITEM_ID" OtherKey="ITEM_ID" Type="Item" IsForeignKey="true" />
      <Association Name="PropValue_Connector" Member="PropValue" ThisKey="VALUE_ID" OtherKey="VALUE_ID" Type="PropValue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="ITEM_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHOTO" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="PRICE_PER_DAY" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="STATE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Item_Connector" Member="Connectors" ThisKey="ITEM_ID" OtherKey="ITEM_ID" Type="Connector" />
      <Association Name="Item_Reservation" Member="Reservations" ThisKey="ITEM_ID" OtherKey="ITEM_ID" Type="Reservation" />
      <Association Name="State_Item" Member="State" ThisKey="STATE_ID" OtherKey="STATE_ID" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Properties" Member="Properties">
    <Type Name="Property">
      <Column Name="PROPERTY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Property_PropValue" Member="PropValues" ThisKey="PROPERTY_ID" OtherKey="PROPERTY_ID" Type="PropValue" />
    </Type>
  </Table>
  <Table Name="dbo.PropValues" Member="PropValues">
    <Type Name="PropValue">
      <Column Name="VALUE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VALUE" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PROPERTY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PropValue_Connector" Member="Connectors" ThisKey="VALUE_ID" OtherKey="VALUE_ID" Type="Connector" />
      <Association Name="Property_PropValue" Member="Property" ThisKey="PROPERTY_ID" OtherKey="PROPERTY_ID" Type="Property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="RESERVATION_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DATE_FROM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DATE_TO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ORDER_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OVERALL_PRICE" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ITEM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Reservation" Member="Item" ThisKey="ITEM_ID" OtherKey="ITEM_ID" Type="Item" IsForeignKey="true" />
      <Association Name="ReservationStatuse_Reservation" Member="ReservationStatuse" ThisKey="STATUS_ID" OtherKey="STATUS_ID" Type="ReservationStatuse" IsForeignKey="true" />
      <Association Name="User_Reservation" Member="User" ThisKey="USER_ID" OtherKey="USER_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservationStatuses" Member="ReservationStatuses">
    <Type Name="ReservationStatuse">
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="ReservationStatuse_Reservation" Member="Reservations" ThisKey="STATUS_ID" OtherKey="STATUS_ID" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="ROLE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Role_User" Member="Users" ThisKey="ROLE_ID" OtherKey="ROLE_ID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="STATE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATE_NAME" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="State_Item" Member="Items" ThisKey="STATE_ID" OtherKey="STATE_ID" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LOGIN" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SURNAME" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ROLE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Reservation" Member="Reservations" ThisKey="USER_ID" OtherKey="USER_ID" Type="Reservation" />
      <Association Name="Role_User" Member="Role" ThisKey="ROLE_ID" OtherKey="ROLE_ID" Type="Role" IsForeignKey="true" />
      <Association Name="UsersAdress_User" Member="UsersAdress" ThisKey="ADRESS_ID" OtherKey="ADRESS_ID" Type="UsersAdress" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersAdresses" Member="UsersAdresses">
    <Type Name="UsersAdress">
      <Column Name="ADRESS_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STREET_NAME" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="STREET_NUMBER" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="POSSESION_NUMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UsersAdress_User" Member="Users" ThisKey="ADRESS_ID" OtherKey="ADRESS_ID" Type="User" />
    </Type>
  </Table>
</Database>