//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\aspnet-WebApp" +
            "lication1-20160819032236.mdf;Initial catalog=MyGraduationProjectDatabase;Integra" +
            "ted Security=True;MultipleActiveResultSets=True;")]
        public string MyGraduationProject_DatabaseConnectionString {
            get {
                return ((string)(this["MyGraduationProject_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\aspnet-WebApp" +
            "lication1-20160819032236.mdf;Initial Catalog=MyGraduationProjectDatabase;Integra" +
            "ted Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" +
            "")]
        public string MyGraduationProjectDatabaseConnectionString {
            get {
                return ((string)(this["MyGraduationProjectDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=C:\Users\Misiek\Desktop\MyGraduationProject\MyGraduationProject\App_Data\aspnet-WebApplication1-20160819032236.mdf;Initial Catalog=MyGraduationProjectDatabase;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string MyGraduationProjectDatabaseConnectionString1 {
            get {
                return ((string)(this["MyGraduationProjectDatabaseConnectionString1"]));
            }
        }
    }
}
